apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./tekton/
  - ./gitops/
  - ./talm/
  - ./gatekeeper/
  - ./loki/
  - ./cluster-logging/
  - ./data-foundation/
  - ./acs/
  - ./acm/

