---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./tekton/
  - ./gitops/
  - ./talm/
  - ./gatekeeper/
  - ./loki/
  - ./cluster-logging/
  - ./cluster-observability/
  - ./data-foundation/
  - ./acs/
  - ./acm/
  - ./network-observability/
  - ./kiali/
  - ./servicemesh/
  - ./opentelemetry/
  - ./tempo/
  - ./ansible-automation-platform/
  - ./developer-hub/
  - ./workload-availability/
  - ./cert-manager/
  - ./compliance-operator/
  - ./external-secrets/
  - ./file-integrity/
  - ./secondary-scheduler
